# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Image',
            new_name='image',
        ),
    ]
