# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181219_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.FileField(null=True, upload_to='products/images/'),
        ),
    ]
