# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181219_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
    ]
