# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
    ]
